pipeline:
  build:
    image: nixos/nix:latest
    commands:
      - nix-shell --run 'cargo build --release --target aarch64-unknown-linux-musl'
  publish:
    when:
      event: tag
    image: woodpeckerci/plugin-gitea-release
    settings:
      base_url: https://git.blizzard.systems
      files:
        - "target/aarch64-unknown-linux-musl/release/seymour_life"
      checksum: 
        - "target/aarch64-unknown-linux-musl/release/seymour_life"
      api_key:
        from_secret: API_KEY
      target: stable
      draft: true
      prerelease: true
      title: .woodpecker/title.txt
